#!/usr/bin/env python

'''
Performs a binary search on a list of inputs provided over standard input, running the provided
command (substituting `{}` with the current input, ala xargs) until two adjacent inputs`$input_a`
and `$input_b` are found such that `cmd $input_a` exits 0 and `cmd $input_b` exits non-zero.
'''

from bisect import bisect_right
import subprocess
import sys

inputs = sys.stdin.read().splitlines()
command = sys.argv[1:]
def run_command(input):
    actual_command = [ input if token == '{}' else token for token in command ]
    # print(actual_command, file=sys.stderr) # XXX DEBUG
    return subprocess.call(actual_command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

idx = bisect_right(inputs, 0, key=run_command)
print(inputs[idx - 1])
