#!/usr/bin/env perl

use strict;
use warnings;
use feature qw(say);
use experimental qw(signatures);

my @SUFFIXES = (
    [T  => 1_000_000_000_000],
    [G  => 1_000_000_000],
    [M  => 1_000_000],
    [K  => 1_000],
    ['' => 1],
);

while(<>) {
    chomp;

    for my $suffix_tuple (@SUFFIXES) {
        my ( $suffix, $mult ) = @$suffix_tuple;
        if($_ > $mult) {
            printf "%.2f%s\n", $_ / $mult, $suffix;
            last;
        }
    }
}
