#!/bin/bash

export SQLITE_HISTORY=$HOME/.fxsql_history
export LD_LIBRARY_PATH=$HOME/.fxsql_extensions/

filename=$(echo ~/.mozilla/firefox/*.default/places.sqlite)

sqliterc=$(mktemp ${TMPDIR:-/tmp}/fxsql-init.XXXXXX)
cat <<END_SQLITERC > "$sqliterc"
.load url

CREATE TEMPORARY VIEW v AS
  SELECT DATETIME(hv.visit_date / 1000000, 'unixepoch', 'localtime') AS visit_date, p.title, p.url FROM moz_places AS p
  INNER JOIN moz_historyvisits AS hv
  ON hv.place_id = p.id
  ORDER BY hv.visit_date
END_SQLITERC

sqlite3 -batch -init "$sqliterc" "file:$filename?immutable=1" "$@"
rm "$sqliterc"
