#!/bin/bash

export SQLITE_HISTORY=$HOME/.fxsql_history

filename=$(mktemp ${TMPDIR:-/tmp}/fxsql-db.XXXXXX)
cp ~/.mozilla/firefox/*.default/places.sqlite "$filename"
sqlite3 -readonly "$filename" "$@"
rm "$filename"
