#!/usr/bin/env perl

use strict;
use warnings;
use feature qw(say);
use utf8::all;

use Mojo::DOM;

my $dom = do {
    local $/;
    Mojo::DOM->new(<>)
};

my $body = $dom->find('body')->first;
exit unless $body;

$body->find('script, style')->map('remove');

say $body->all_text;
