#!/usr/bin/env perl

# git bisect-status: print out your current git-bisect status
# intended to be run within scripts run via git bisect run, useful when
# combined with set-term-title

use strict;
use warnings;
use feature qw(say);

my @lines = qx(git rev-list --bisect --bisect-vars 2>/dev/null);
exit unless @lines;
chomp @lines;
my %vars = map { /^(\w+)=(\d+)$/ ? ($1, $2) : () } @lines;

my ( $bisect_nr, $bisect_steps ) = @vars{qw/bisect_nr bisect_steps/};

my $rev_plural   = $bisect_nr    == 1 ? '' : 's';
my $steps_plural = $bisect_steps == 1 ? '' : 's';

say "Bisecting: $bisect_nr revision$rev_plural left to test after this (roughly $bisect_steps step$steps_plural)";
