#!/bin/bash

if [[ "$(basename $(readlink /proc/$PPID/exe))" == 'man' ]]; then
    title=man\ $(perl -F'/\0/' -anle 'print($F[-1] =~ s/\x27//gr)' /proc/$PPID/cmdline)
else
    gppid=$(perl -nle 'print $1 if /^PPid:\s*(\d+)/' /proc/$PPID/status)
    if [[ "$(cat /proc/$gppid/comm)" == 'perldoc' ]]; then
        title=perldoc\ $(perl -F'/\0/' -anle 'print($F[-1] =~ s/\x27//gr)' /proc/$gppid/cmdline)
    else
        title="$(< /proc/$PPID/cmdline perl -F'/\0/' -MFile::Basename=basename -anle 'shift @F if basename($F[0]) eq q{python}; $F[0] = basename($F[0]); print(join(q{ }, @F))')"
    fi
fi
title=$(echo "$title" | perl -nle 's/(.)/sprintf("\\x%02x", ord($1))/ger; print')

sed -e 's/\x1b\[[^m]*m//g' $1 | col -b | vim -c "set ft=man noswf noma nomod nolist ignorecase title | let &titlestring=\"$title\"" -
