#!/bin/bash

firefox "$1" &
cat <<END_LUA | awesome-client
local r_match = require('awful.rules').match
local iterate = require('awful.client').iterate
local jumpto  = require('awful.client').jumpto

local function match_firefox(c)
  return r_match(c, { class = 'Firefox' })
end

for c in iterate(match_firefox, 1, nil) do
  if not string.find(c.name, 'Private Browsing') then
    jumpto(c)
    break
  end
end
END_LUA
