#!/usr/bin/env perl

use strict;
use warnings;
use feature qw(say);

die "usage: $0 [package]\n" unless @ARGV;
my ( $pkg ) = @ARGV;
open my $pipe, '-|', 'pacman', '-Ql', $pkg;
while(<$pipe>) {
    chomp;
    my ( undef, $filename ) = split;

    if($filename !~ m{/$}) {
        say $filename;
    }
}
my $status = close $pipe;
if(!$status) {
    warn "pacman encountered an issue (likely reported above) - exiting\n";
}
