#!/usr/bin/env perl

use strict;
use warnings;

# sets the terminal title to the space-separated concatenation
# of the script arguments

my $title = join(' ', @ARGV);

if($ENV{'TMUX'}) {
    print "\ek$title\e\\";
} else {
    print "\e]2;$title\a";
}
