#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo "usage: $0 [exporter address]" >&2
    exit 1
fi

tempdir=$(mktemp -d)

trap 'rm -rf "$tempdir"' EXIT

cat > "$tempdir/prometheus.yml" <<END_CONFIG
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'test-exporter'
    static_configs:
    - targets: ['$1']
END_CONFIG

cd /usr/share/prometheus/
prometheus --web.listen-address="127.0.0.1:0" --web.enable-lifecycle --config.file="$tempdir/prometheus.yml" --storage.tsdb.path="$tempdir/data" &>"$tempdir/prometheus.log" & PROM_PID=$!

sleep 1
echo "listening on $(netstat -nltp 2>/dev/null | grep $PROM_PID | perl -anle 'print $F[3]') - logs are available in $tempdir/prometheus.log"

wait $PROM_PID
