#!/usr/bin/env python

from datetime import datetime
import re

with open('/proc/stat') as f:
    for line in f:
        if m := re.match(r'^btime\s+(\d+)', line):
            btime = float(m.group(1))
            break

with open('/var/log/Xorg.0.log', 'r') as f:
    for line in f:
        line = re.sub(r'^\[(.*?)\]', lambda m: f'[{datetime.fromtimestamp(float(m.group(1))+btime)}]', line)
        print(line, end='')
